FROM alpine:latest

WORKDIR /usr/src/app

RUN apk update && apk add python3 py3-flask

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py ./

COPY . .

# Run the Flask application
CMD [ "python3", "app.py"]
